### ISSUE TITLE
Where is the external folder?

### ISSUE THREAD

**Issue by omichel** [xbpeng/DeepLoco#1]
Thanks for sharing this nice simulation. I am trying to install it, but can't find the `external` folder you are mentioning in the installation instructions. Where is it?

**Comment by xbpeng** [comment]
sorry about that, you can find it here:
https://github.com/xbpeng/DeepTerrainRL/releases

**Comment by Neo-X** [comment]
You can also find them for Windows and Linux here.
https://github.com/xbpeng/DeepLoco/releases/tag/0.81
