### ISSUE TITLE
What's the possible solution for the model loading failure?

### ISSUE THREAD

**Issue by zrdumped** [xbpeng/DeepLoco#10]
I tired some weird ways to setup and compile the code, and finally executed the DeepLoco successfully. There is no error reported, but it seemed that the model could not be loaded , and the only things I could see were some squares like this:
![screenshot](https://user-images.githubusercontent.com/20452072/35136444-9522f264-fd1e-11e7-9278-23359471071e.png)

My OpenGL version is 4.3, which is enough for this project, according to the ReadMe file.
Thx.

**Comment by Neo-X** [comment]
The only other time I have seen something like this before was when DeepLoco was run on a very old GPU. Maybe check that your drivers are up to date.

**Comment by zrdumped** [comment]
It's true that my GPU is very old. I'll try it on another computer & GPU. Thanks a lot.
