### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by jeromepl** [xbpeng/DeepLoco#11]
When trying to build the project on Windows, I end up with the following error (after following the installation steps and putting required librairies at the right places):
```
Error: LNK2038	mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in blob.obj	DeepLoco	File: BulletDynamics_Debug.lib(btRigidBody.obj)	Line: 1	
```

which seems to indicate that Bullet was compiled for a different Visual Studio version.
I am using Visual Studio 2017, and tried using VS2015 but encountered another error related to Platform Toolset.

**Comment by Neo-X** [comment]
This setup has been tested on Windows 7 and 10 with visual studio 2013. We can't guarantee it will work for other versions of ms studio.
