### ISSUE TITLE
Definition of reference motion angles from mocap

### ISSUE THREAD

**Issue by XuanLin** [xbpeng/DeepLoco#13]
Hello,

May I ask a question on the reference motion from mocap?

It looks like to me that the reference motion lies in the folder DeepLoco/data/motions/mocap/biped3d_walk/ as separate files of 28x30 matrices. If I am correct, then what does each row and each column stand for? From the paper the walker has 15 degree of freedom (3+3+1 for each leg and 1 for torso), it doesn't look like the dimension matches the degree of freedom (if each row or column represents one frame).

Thank you!

![frames](https://user-images.githubusercontent.com/10069542/37194753-98b3cc92-2324-11e8-89c8-762ca6b8f60a.PNG)

**Comment by xbpeng** [comment]
each row corresponds to a keyframe. The first number is the duration of the frame, the first 7 numbers are the position (3) and rotation in quaternions (4) of the root. Then its the pose of every joint. The humanoid has spherical joints (specified as 4D quaternions), so they are not just 1D.

**Comment by XuanLin** [comment]
Thanks! That is exactly what I want to know!

**Comment by hwiedPro** [comment]
For which walking speed of the human where the motions recorded?
Do the human leg lengths (femur/crus) match the leg lengths of the robot?
What are the lengths?

**Comment by Neo-X** [comment]
The data in the motion files follows the same syntax as the state files https://github.com/xbpeng/DeepLoco/wiki/State-Files. The motions were based on data converted from http://mocap.cs.sfu.ca/, I think that walking speed for the mocap is between 1 and 1.3m/s. The simulated character used in DeepLoco is similar to the mocap character but not the same.
