### ISSUE TITLE
cannot find -lBulletDynamics_gmake_x64_debug

### ISSUE THREAD

**Issue by epsilonkei** [xbpeng/DeepLoco#18]
I am following the instruction in README.md to build instructions of your project.
I have successfully built the source code for `caffe` and finished copy prebuilt libraries from the external folder.
Then, I run the command `make config=debug64`.
However, the compilation stopped with this error:
```
==== Building deepLocoUtil (debug64) ====
==== Building deepLocoAnim (debug64) ====
==== Building deepLocoLearning (debug64) ====
==== Building deepLocoSim (debug64) ====
==== Building deepLocoRender (debug64) ====
==== Building deepLocoScenarios (debug64) ====
==== Building DeepLoco_Optimizer (debug64) ====
Linking DeepLoco_Optimizer
/usr/bin/ld: -lBulletDynamics_gmake_x64_debug が見つかりません
/usr/bin/ld: -lBulletCollision_gmake_x64_debug が見つかりません
/usr/bin/ld: -lLinearMath_gmake_x64_debug が見つかりません
collect2: error: ld returned 1 exit status
make[1]: *** [../x64/Debug/DeepLoco_Optimizer] エラー 1
make: *** [DeepLoco_Optimizer] エラー 2
```
(The error was written in Japanese, but it means 
```
/usr/bin/ld: cannot find -lBulletDynamics_gmake_x64_debug
/usr/bin/ld: cannot find -lBulletCollision_gmake_x64_debug 
/usr/bin/ld: cannot find -lLinearMath_gmake_x64_debug 
```
)
My OS environment is Ubuntu 14.04.
Could anyone please help? Thanks alot for your time.

**Comment by Neo-X** [comment]
This is a known issue.

You can either go into the external/Bullet/build folder and compile the debug libraries. Or a simpler solution which should be done is to use the release libraries for bullet even when compiling the code into debug mode.
