### ISSUE TITLE
Error compile caffe with caffe_mods

### ISSUE THREAD

**Issue by tuanphuc** [xbpeng/DeepLoco#2]
First, thank you for opensourcing your project.

I have a problem compiling caffe with caffe_mods. When I clone the specific version (https://github.com/niuzhiheng/caffe.git @ 7b3e6f2341fe7374243ee0126f5cad1fa1e44e14), there is no folders layers under include/caffe to add:
  -  caffe_mods/fixed_euclidean_loss_layer.hpp
  -  caffe_mods/weighted_euclidean_loss_layer.hpp

So I suppose that you copied the README.md of https://github.com/xbpeng/DeepTerrainRL without modifying the caffe version. 
Then I clone the official caffe https://github.com/BVLC/caffe, add files in caffe_mods and compile but I get the error: 

CXX src/caffe/layers/infogain_loss_layer.cpp
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:18:3: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   softmax_param->set_axis(this->layer_param_.infogain_loss_param().axis());
   ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:55:18: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   infogain_axis_ =
                  ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:18:3: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   softmax_param->set_axis(this->layer_param_.infogain_loss_param().axis());
   ^
src/caffe/layers/infogain_loss_layer.cpp: In instantiation of ‘void caffe::InfogainLossLayer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/infogain_loss_layer.cpp:221:1:   required from here
src/caffe/layers/infogain_loss_layer.cpp:55:18: error: ‘const class caffe::InfogainLossParameter’ has no member named ‘axis’
   infogain_axis_ =
                  ^
Makefile:581: recipe for target '.build_release/src/caffe/layers/infogain_loss_layer.o' failed
make: *** [.build_release/src/caffe/layers/infogain_loss_layer.o] Error 1

Can you precise the caffe version needed to be compiled with files in caffe_mods ? Thank you

**Comment by Neo-X** [comment]
You need to use our custom version of caffe.
See the first step of the build instructions https://github.com/xbpeng/DeepLoco#build-instructions.
You can find them here
https://github.com/xbpeng/DeepLoco/releases/tag/0.81

**Comment by tuanphuc** [comment]
Thank you very much. I downloaded the release and compiled successfully caffe

**Comment by zllljf** [comment]
i meet the same problem, with other object, What is the nature of the problem？What is the general solution？

**Comment by wangxinyue11** [comment]
> 我遇到另一个对象是同一问题，该问题的性质是什么？一般的解决方案是什么？

我也遇到了同样的问题，请问你是如何解决的？
