### ISSUE TITLE
Cannot open final file on ubuntu16.04

### ISSUE THREAD

**Issue by chongyang-guo** [xbpeng/DeepLoco#22]
I followed the steps to generate the Final document in the/DeepLoco-master/x64/Debug on ubuntu16.04, but I can't open them.so I try it at the terminal，but  it tell me that ./DeepLoco: error while loading shared libraries: libBulletDynamics_gmake_x64_release.so: cannot open shared object file: No such file or directory.
I want to know if the location of the executable I generated is incorrect or my process is wrong.Thank you very much for your answer.

**Comment by Neo-X** [comment]
Step 5 in the [Build Instructions](https://github.com/xbpeng/DeepLoco#build-instructions) has you copy these files to the ./lib folder. Did this work?

**Comment by chongyang-guo** [comment]
> Step 5 in the [Build Instructions](https://github.com/xbpeng/DeepLoco#build-instructions) has you copy these files to the ./lib folder. Did this work?

Thank you!The problem has been found，but But still can't work，because my openGL version is too low.
