### ISSUE TITLE
About the CNN model

### ISSUE THREAD

**Issue by WatsonZhou12** [xbpeng/DeepLoco#26]
Hi, 
I noticed that in your paper, you process the terrain map by there convolutional layers in HLC network, and your filters are 16 5×5, 32 4×4, and 32 3×3 respectively.

However, I found that in your source code (keras folder: deepLoco_model.py), the number of convolutional layers is 9, and the filters are 16 5×5, 16 5×5, 64 5×5, 64 5×5, 64 5×5, 256 3×3, 256 3×3, 256 3×3, 256 3×3 respectively. 

So I would like to know is this file wrong? Maybe the right CNN model is not in this file?

Thanks in advance! @xbpeng @Neo-X

**Comment by xbpeng** [comment]
The CNN is defined here:
https://github.com/xbpeng/DeepLoco/blob/master/data/policies/biped3d/nets/biped3d_hlc_actor_net.prototxt
There are only three conv layers, the other layers are fully connected layers.

**Comment by WatsonZhou12** [comment]
Ok, I got it. Thanks!
