### ISSUE TITLE
DeepLoco crashes

### ISSUE THREAD

**Issue by hframa** [xbpeng/DeepLoco#6]
Hi, I managed to successfully build the project on my Ubuntu 16.04 and copied all files from `x64/Debug` to the root folder.

When I try to run DeepLoco using the command `./DeepLoco -arg_file= args/test_args.txt`

The program crashes with `Segmentation fault (core dumped)` :

(for full output: [log.txt](https://github.com/xbpeng/DeepLoco/files/1463082/log.txt) )
... 

I1110 23:59:07.444648  4474 net.cpp:274] Network initialization done.
Compiling shader: render/shaders/Mesh_VS.glsl
Compiling shader: render/shaders/Depth_PS.glsl
Compiling shader: render/shaders/Mesh_VS.glsl
Compiling shader: render/shaders/Lighting_Lambert_PS.glsl
Char Draw Shapes Disabled
Loaded scenario: Imitate Step Evaluation
*** Aborted at 1510358347 (unix time) try "date -d @1510358347" if you are using GNU date ***
PC: @           0x64a872 btCollisionObject::getActivationState()
*** SIGSEGV (@0x7fbb000004ed) received by PID 4474 (TID 0x7fbb4cb92b00) from PID 1261; stack trace: ***
    @     0x7fbb4a09a4b0 (unknown)
    @           0x64a872 btCollisionObject::getActivationState()
    @           0x68725b btSimulationIslandManager::addManifoldsToIslands()
    @           0x687ac8 btSimulationIslandManager::buildAndProcessIslands()
    @           0x645b28 btDiscreteDynamicsWorld::solveConstraints()
    @           0x64507f btDiscreteDynamicsWorld::internalSingleStepSimulation()
    @           0x644e93 btDiscreteDynamicsWorld::stepSimulation()
    @           0x565b40 cWorld::Update()
    @           0x476ddd cScenarioSimChar::UpdateWorld()
    @           0x475311 cScenarioSimChar::Update()
    @           0x442a14 cScenarioExp::Update()
    @           0x48978c cScenarioExpImitateTarget::Update()
    @           0x4512f2 cDrawScenarioSimChar::UpdateScene()
    @           0x44bae5 cDrawScenarioTerrainRL::Update()
    @           0x450c28 cDrawScenarioSimChar::Update()
    @           0x425c8e UpdateScenario()
    @           0x426627 Update()
    @           0x42677a Animate()
    @     0x7fbb4af73894 glutMainLoopEvent
    @     0x7fbb4af74145 glutMainLoop
    @           0x42e72e main
    @     0x7fbb4a085830 __libc_start_main
    @           0x4104b9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

Note: I installed pybullet using `pip install pybullet` since the build procedure wasn't able to find pre-built Bullet libraries (#5).

**Comment by xbpeng** [comment]
you should be able to find the prebuilt libs at 
https://github.com/xbpeng/DeepLoco/releases

**Comment by hframa** [comment]
@xbpeng Thanks for the reply.
The prebuilt version contains **release** version of Bullet library files, instead of **debug** version that are needed to build the project.

**Comment by hframa** [comment]
Fixed it by using Bullet libs from eternal. Had to copy and rename release files to debug (#5)
