### ISSUE TITLE
shader linking failed

### ISSUE THREAD

**Issue by ghost** [xbpeng/DeepLoco#8]
Have you ever encountered this problem? is a cause also due to opengl? My OpenGL version is 4.5 and i use Quadro M4000 (NVIDIA) and OS is Ubuntu 16.04. I don't use OpenGL 3.3 needed oon intel HD Graphics. The small window whose title is TerrainRL was displayed but there is not displayed at all. The color of window is kept gray. When I pushed a key "q" on the small window, "Filmstrip mode enabled" is shown on the terminal. i think your logic itself is running in the back of the gray window. On my same machine, I tried your previous logic (Deep Terrain Learning). It was run and the good animation was displayed smoothly without any problem. I want to fix the window's condition being gray color. I runed from x64/Debug. I need your help.

~$ DeepLoco -arg_file=args/test_args.txt
 Compiling shader: render/shaders/FullScreenQuad_VS.glsl
 Compiling shader: render/shaders/DownSample_PS.glsl
 shader linking failed
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501
 Buffer Assignment Failed: 00000501

**Comment by Neo-X** [comment]
Make sure you are rendering using the Nvidia card. I have had issues with the intel HD drivers on Ubuntu. I get the same issue you reported. You can also try the code on another computer.
