### ISSUE TITLE
How to train for running?

### ISSUE THREAD

**Issue by minostauros** [xbpeng/DeepLoco#9]
The codes seems to be quite sophisticated and I'm not familiar with the libraries used, so here's a quickie question:

I successfully trained given scenarios, but I cannot find a scenario to train 'running'. 
How can the LLC be trained for running?

**Comment by xbpeng** [comment]
sorry, but this only supports training for walking at the moment

**Comment by minostauros** [comment]
> sorry, but this only supports training for walking at the moment

So just modifying the codes won't result in running motion unless additional external resources are given..?

**Comment by Neo-X** [comment]
Correct, this has more to do with the running motion capture needed to train with.
